// GENERATED from cruisn-collection/gpu/renderer.py - regenerate with harness/gen_shaders.py, never hand-edit

static const char *MVGL_VS =
	"\n"
	"#version 430\n"
	"uniform vec2 uCanvas;      // coarse canvas size (W, H)\n"
	"in vec2 in_corner;         // bbox corner, coarse pixel space\n"
	"in vec2 in_v0; in vec2 in_v1; in vec2 in_v2; in vec2 in_v3;\n"
	"in vec4 in_uv01;           // u0,v0,u1,v1\n"
	"in vec4 in_uv23;           // u2,v2,u3,v3\n"
	"in uvec4 in_meta;          // pixdata, mode, dither, texbase\n"
	"flat out vec2 v0; flat out vec2 v1; flat out vec2 v2; flat out vec2 v3;\n"
	"flat out vec4 uv01; flat out vec4 uv23;\n"
	"flat out uvec4 meta;\n"
	"void main() {\n"
	"    v0 = in_v0; v1 = in_v1; v2 = in_v2; v3 = in_v3;\n"
	"    uv01 = in_uv01; uv23 = in_uv23; meta = in_meta;\n"
	"    // y-down pixel space -> NDC (y flipped)\n"
	"    gl_Position = vec4(in_corner.x / uCanvas.x * 2.0 - 1.0,\n"
	"                       1.0 - in_corner.y / uCanvas.y * 2.0, 0.0, 1.0);\n"
	"}\n"
	"\n";

static const char *MVGL_FS =
	"\n"
	"#version 430\n"
	"uniform int  uScale;       // 1 = exact mode, >1 = quality mode\n"
	"uniform vec2 uCanvas;      // coarse canvas size\n"
	"uniform int  uClipRight;   // coarse cliprect right (W-1)\n"
	"uniform usampler2D texram; // 4096-wide R8UI, 8 MB of texture RAM\n"
	"uniform int  texMask;      // byte-size mask (size-1)\n"
	"uniform int  uDbgQuadId;   // debug: if 1, outIndex = quad id (gl_PrimitiveID/2)\n"
	"uniform int  uBgMargin;    // coarse margin width; backdrop quads discarded\n"
	"                           // inside the margins so extend fills from the\n"
	"                           // 4:3 boundary (sky above, terrain below). 0=off.\n"
	"uniform int  uClipW;       // coarse canvas width (for the right margin)\n"
	"flat in vec2 v0; flat in vec2 v1; flat in vec2 v2; flat in vec2 v3;\n"
	"flat in vec4 uv01; flat in vec4 uv23;\n"
	"flat in uvec4 meta;\n"
	"layout(location = 0) out uint outIndex;\n"
	"layout(location = 1) out uint outMask;   // 1 = this scene wrote the pixel\n"
	"\n"
	"int round_coord(float f) {           // poly.h: floor, +1 iff frac > 0.5\n"
	"    float ip = floor(f);\n"
	"    return int(ip) + (((f - ip) > 0.5) ? 1 : 0);\n"
	"}\n"
	"int c_int32(float f) {               // C float->int32: trunc, OOR -> INT_MIN\n"
	"    if (!(abs(f) < 2147483648.0)) return -2147483648;\n"
	"    return int(f);\n"
	"}\n"
	"uint fetch_texel(int idx) {\n"
	"    idx &= texMask;\n"
	"    return texelFetch(texram, ivec2(idx & 4095, idx >> 12), 0).r;\n"
	"}\n"
	"\n"
	"void main() {\n"
	"    vec2 vx[4] = vec2[4](v0, v1, v2, v3);\n"
	"    float fx = gl_FragCoord.x;\n"
	"    float fy = uCanvas.y * float(uScale) - gl_FragCoord.y;   // y-down\n"
	"    float cx = fx / float(uScale);\n"
	"    float cy = fy / float(uScale);\n"
	"    int px = int(floor(cx));\n"
	"    int py = int(floor(cy));\n"
	"    // exact mode evaluates at MAME's scanline centre; quality mode uses the\n"
	"    // fine fragment's own continuous coordinate\n"
	"    precise float fully = (uScale == 1) ? float(py) + 0.5 : cy;\n"
	"\n"
	"    // ---- min/max Y vertices (poly.h render_polygon) ----\n"
	"    int minv = 0, maxv = 0;\n"
	"    for (int i = 1; i < 4; i++) {\n"
	"        if (vx[i].y < vx[minv].y) minv = i;\n"
	"        else if (vx[i].y > vx[maxv].y) maxv = i;\n"
	"    }\n"
	"    if (round_coord(vx[maxv].y) - round_coord(vx[minv].y) <= 0) discard;\n"
	"    float maxvy = vx[maxv].y;\n"
	"\n"
	"    // poly.h renders scanlines [round(miny), round(maxy)) only - the expanded\n"
	"    // bounding box generates fragments beyond that, where extrapolated edges\n"
	"    // still yield plausible x-extents. Without this cut, later quads steal\n"
	"    // their neighbours' shared-edge rows.\n"
	"    if (uScale == 1) {\n"
	"        if (py < round_coord(vx[minv].y) || py >= round_coord(maxvy)) discard;\n"
	"    } else {\n"
	"        if (cy < vx[minv].y || cy >= maxvy) discard;\n"
	"    }\n"
	"\n"
	"    // ---- forward / backward edge lists (<=3 each) ----\n"
	"    // e[k] = (v1x, v1y, v2y, dxdy), p[k] = (u1, v1_p, dudy, dvdy)\n"
	"    precise vec4 fe[3]; precise vec4 fp[3]; int fn = 0;\n"
	"    precise vec4 be[3]; precise vec4 bp[3]; int bn = 0;\n"
	"    vec4 uvs[4] = vec4[4](vec4(uv01.xy, 0, 0), vec4(uv01.zw, 0, 0),\n"
	"                          vec4(uv23.xy, 0, 0), vec4(uv23.zw, 0, 0));\n"
	"    for (int curv = minv; curv != maxv; curv = (curv + 1) & 3) {\n"
	"        int nxt = (curv + 1) & 3;\n"
	"        if (vx[nxt].y != vx[curv].y) {\n"
	"            precise float ooy = 1.0 / (vx[nxt].y - vx[curv].y);\n"
	"            fe[fn] = vec4(vx[curv].x, vx[curv].y, vx[nxt].y,\n"
	"                          (vx[nxt].x - vx[curv].x) * ooy);\n"
	"            fp[fn] = vec4(uvs[curv].xy,\n"
	"                          (uvs[nxt].x - uvs[curv].x) * ooy,\n"
	"                          (uvs[nxt].y - uvs[curv].y) * ooy);\n"
	"            fn++;\n"
	"        }\n"
	"    }\n"
	"    for (int curv = minv; curv != maxv; curv = (curv - 1) & 3) {\n"
	"        int nxt = (curv - 1) & 3;\n"
	"        if (vx[nxt].y != vx[curv].y) {\n"
	"            precise float ooy = 1.0 / (vx[nxt].y - vx[curv].y);\n"
	"            be[bn] = vec4(vx[curv].x, vx[curv].y, vx[nxt].y,\n"
	"                          (vx[nxt].x - vx[curv].x) * ooy);\n"
	"            bp[bn] = vec4(uvs[curv].xy,\n"
	"                          (uvs[nxt].x - uvs[curv].x) * ooy,\n"
	"                          (uvs[nxt].y - uvs[curv].y) * ooy);\n"
	"            bn++;\n"
	"        }\n"
	"    }\n"
	"    if (fn == 0 || bn == 0) discard;\n"
	"\n"
	"    // ---- left/right decision (poly.h:1194) ----\n"
	"    bool sharedFirst = (fe[0].x == be[0].x) && (fe[0].y == be[0].y);\n"
	"    bool fwd_left = (sharedFirst && fe[0].w < be[0].w)\n"
	"                 || (!sharedFirst && fe[0].x < be[0].x);\n"
	"\n"
	"    // ---- advance to the edge pair spanning this scanline ----\n"
	"    int li = 0, ri = 0;\n"
	"    vec4 le, lp, re, rp;\n"
	"    if (fwd_left) {\n"
	"        while (fully > fe[li].z && fully < maxvy && li + 1 < fn) li++;\n"
	"        while (fully > be[ri].z && fully < maxvy && ri + 1 < bn) ri++;\n"
	"        le = fe[li]; lp = fp[li]; re = be[ri]; rp = bp[ri];\n"
	"    } else {\n"
	"        while (fully > be[li].z && fully < maxvy && li + 1 < bn) li++;\n"
	"        while (fully > fe[ri].z && fully < maxvy && ri + 1 < fn) ri++;\n"
	"        le = be[li]; lp = bp[li]; re = fe[ri]; rp = fp[ri];\n"
	"    }\n"
	"\n"
	"    precise float startx = le.x + (fully - le.y) * le.w;\n"
	"    precise float stopx  = re.x + (fully - re.y) * re.w;\n"
	"    int istartx = round_coord(startx);\n"
	"    int istopx  = round_coord(stopx);\n"
	"    if (istartx > istopx) { int t = istartx; istartx = istopx; istopx = t; }\n"
	"\n"
	"    // ---- params at this scanline (poly.h:1250) ----\n"
	"    precise float ldy = fully - le.y;\n"
	"    precise float rdy = fully - re.y;\n"
	"    precise float oox = 1.0 / (stopx - startx);\n"
	"    precise float lu = lp.x + ldy * lp.z;\n"
	"    precise float lv = lp.y + ldy * lp.w;\n"
	"    precise float dudx = (rp.x + rdy * rp.z - lu) * oox;\n"
	"    precise float dvdx = (rp.y + rdy * rp.w - lv) * oox;\n"
	"    precise float su = lu + (float(istartx) + 0.5 - startx) * dudx;\n"
	"    precise float sv = lv + (float(istartx) + 0.5 - startx) * dvdx;\n"
	"\n"
	"    // ---- left/right clip with param adjust ----\n"
	"    if (istartx < 0) {\n"
	"        su += float(-istartx) * dudx;\n"
	"        sv += float(-istartx) * dvdx;\n"
	"        istartx = 0;\n"
	"    }\n"
	"    if (istopx > uClipRight) istopx = uClipRight + 1;\n"
	"    if (istartx >= istopx) discard;\n"
	"\n"
	"    // ---- coverage ----\n"
	"    if (uScale == 1) {\n"
	"        if (px < istartx || px >= istopx) discard;\n"
	"    } else {\n"
	"        // continuous edges at fine resolution; clip window still applies\n"
	"        float lo = max(min(startx, stopx), 0.0);\n"
	"        float hi = min(max(startx, stopx), float(uClipRight + 1));\n"
	"        if (cx < lo || cx >= hi) discard;\n"
	"    }\n"
	"\n"
	"    uint pixdata = meta.x, mode = meta.y, dither = meta.z & 1u;\n"
	"    bool backdrop = (meta.z & 2u) != 0u;\n"
	"    // suppress backdrop (sky/horizon band) in the 16:9 margins: leaves the\n"
	"    // pixel unwritten so the margin-extend fills it from the 4:3 boundary\n"
	"    // column - sky in the upper margin, terrain in the lower (covers the\n"
	"    // \"water through the ground\" reveal). Terrain/rock quads are unaffected.\n"
	"    if (backdrop && uBgMargin > 0 && (px < uBgMargin || px >= uClipW - uBgMargin))\n"
	"        discard;\n"
	"    if (dither == 1u && ((px ^ py) & 1) != 0) discard;   // coarse-space mask\n"
	"\n"
	"    outMask = 1u;   // every non-discarded fragment marks its pixel written\n"
	"    if (uDbgQuadId == 1) { outIndex = uint(gl_PrimitiveID / 2); return; }\n"
	"    if (mode == 0u) { outIndex = pixdata & 0xffffu; return; }\n"
	"\n"
	"    int ui, vi;\n"
	"    if (uScale == 1) {   // MAME's integer DDA, analytically\n"
	"        ui = c_int32(su) + (px - istartx) * c_int32(dudx);\n"
	"        vi = c_int32(sv) + (px - istartx) * c_int32(dvdx);\n"
	"    } else {             // sub-pixel float interpolation\n"
	"        ui = c_int32(lu + (cx - startx) * dudx);\n"
	"        vi = c_int32(lv + (cx - startx) * dvdx);\n"
	"    }\n"
	"    uint texel = fetch_texel(int(meta.w) + ((vi >> 8) & 0xff00) + (ui >> 16));\n"
	"    if (mode == 1u)      outIndex = (pixdata + texel) & 0xffffu;\n"
	"    else if (mode == 2u) { if (texel == 0u) discard;\n"
	"                           outIndex = (pixdata + texel) & 0xffffu; }\n"
	"    else                 { if (texel == 0u) discard;\n"
	"                           outIndex = pixdata & 0xffffu; }\n"
	"}\n"
	"\n";

static const char *MVGL_PAL_VS =
	"\n"
	"#version 430\n"
	"out vec2 uv;\n"
	"void main() {  // full-screen triangle\n"
	"    vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);\n"
	"    uv = p;\n"
	"    gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);\n"
	"}\n"
	"\n";

static const char *MVGL_PAL_FS =
	"\n"
	"#version 430\n"
	"uniform usampler2D idxTex;\n"
	"uniform usampler2D palTex;   // 256x128 R32UI - 32768 palette words\n"
	"uniform int uCrop;           // fine pixels to crop from each side (2D screens)\n"
	"uniform int uCrt;            // 1 = CRT pass (mask+scanline+curvature), 0 = raw\n"
	"uniform float uSrcH;         // simulated source scanline count (coarse height)\n"
	"uniform usampler2D maskTex;  // R8UI: 1 = written by the CURRENT scene\n"
	"uniform int uFillR;          // crack-fill search radius in fine px; 0 = off\n"
	"uniform int uMargin;         // margin width in fine px for clamp-extend; 0 = off\n"
	"in vec2 uv;\n"
	"out vec4 color;\n"
	"\n"
	"ivec2 fill_px(ivec2 p) {\n"
	"    // Crack fill: the hardware leaves sub-pixel gaps between adjacent quads\n"
	"    // where the page's PREVIOUS frame shows through (authentic, but it\n"
	"    // shimmers). An unwritten pixel is redirected to its nearest written\n"
	"    // neighbour - only when written pixels exist on BOTH sides along some\n"
	"    // axis (a true between-polys crack). One-sided pixels (silhouettes\n"
	"    // against the cleared 16:9 margins) are left untouched.\n"
	"    if (uFillR == 0 || texelFetch(maskTex, p, 0).r != 0u) return p;\n"
	"    ivec2 sz = textureSize(maskTex, 0);\n"
	"    int dl = 0, dr = 0, du = 0, dd = 0;\n"
	"    for (int i = 1; i <= uFillR; i++) {\n"
	"        if (dl == 0 && p.x - i >= 0\n"
	"            && texelFetch(maskTex, p - ivec2(i, 0), 0).r != 0u) dl = i;\n"
	"        if (dr == 0 && p.x + i < sz.x\n"
	"            && texelFetch(maskTex, p + ivec2(i, 0), 0).r != 0u) dr = i;\n"
	"        if (du == 0 && p.y - i >= 0\n"
	"            && texelFetch(maskTex, p - ivec2(0, i), 0).r != 0u) du = i;\n"
	"        if (dd == 0 && p.y + i < sz.y\n"
	"            && texelFetch(maskTex, p + ivec2(0, i), 0).r != 0u) dd = i;\n"
	"    }\n"
	"    int wh = (dl > 0 && dr > 0) ? dl + dr : 1 << 20;\n"
	"    int wv = (du > 0 && dd > 0) ? du + dd : 1 << 20;\n"
	"    if (min(wh, wv) >= (1 << 20)) {\n"
	"        // not a crack. Margin extend: the 16:9 margins show black holes\n"
	"        // where the game's 4:3-era culling never drew - clamp-extend the\n"
	"        // nearest written hardware-boundary pixel. The outermost COVERED\n"
	"        // column sits a couple of fine pixels inside the nominal edge\n"
	"        // (vertices carry a +0.5 coarse offset), so probe a short inward\n"
	"        // run rather than the exact edge column.\n"
	"        if (uMargin > 0) {\n"
	"            if (p.x < uMargin + 8) {\n"
	"                int start = max(p.x + 1, uMargin);\n"
	"                for (int k = start; k <= uMargin + 8; k++) {\n"
	"                    ivec2 q = ivec2(k, p.y);\n"
	"                    if (texelFetch(maskTex, q, 0).r != 0u) return q;\n"
	"                }\n"
	"            } else if (p.x >= sz.x - uMargin - 8) {\n"
	"                int start = min(p.x - 1, sz.x - 1 - uMargin);\n"
	"                for (int k = start; k >= sz.x - 1 - uMargin - 8; k--) {\n"
	"                    ivec2 q = ivec2(k, p.y);\n"
	"                    if (texelFetch(maskTex, q, 0).r != 0u) return q;\n"
	"                }\n"
	"            }\n"
	"        }\n"
	"        return p;\n"
	"    }\n"
	"    if (wh <= wv) return p + ((dl <= dr) ? ivec2(-dl, 0) : ivec2(dr, 0));\n"
	"    return p + ((du <= dd) ? ivec2(0, -du) : ivec2(0, dd));\n"
	"}\n"
	"\n"
	"vec3 fetch_at(ivec2 p) {\n"
	"    p = fill_px(p);\n"
	"    uint pen = texelFetch(idxTex, p, 0).r & 0x7fffu;\n"
	"    uint w = texelFetch(palTex, ivec2(pen & 255u, pen >> 8), 0).r;\n"
	"    uint r = (w >> 10) & 31u, g = (w >> 5) & 31u, b = w & 31u;\n"
	"    return vec3(float((r << 3) | (r >> 2)) / 255.0,\n"
	"                float((g << 3) | (g >> 2)) / 255.0,\n"
	"                float((b << 3) | (b >> 2)) / 255.0);\n"
	"}\n"
	"\n"
	"ivec2 src_px(vec2 tuv) {\n"
	"    ivec2 sz = textureSize(idxTex, 0);\n"
	"    return ivec2(float(uCrop) + tuv.x * float(sz.x - 2 * uCrop),\n"
	"                 tuv.y * float(sz.y));\n"
	"}\n"
	"\n"
	"vec3 fetch_smooth(ivec2 p) {\n"
	"    // Margin sky streak fix: the clamp-extend in fill_px redirects each\n"
	"    // margin pixel to its own row's boundary column, so the boundary's\n"
	"    // per-row cloud/dither detail smears into horizontal streaks across the\n"
	"    // synthetic 16:9 margins. Vertically average the fill (a soft gradient,\n"
	"    // exactly what a stretched sky should look like). Only margin-region\n"
	"    // UNWRITTEN pixels are touched; real geometry is one tap as before, and\n"
	"    // with uMargin==0 (exact / 4:3) this is a straight passthrough.\n"
	"    if (uMargin > 0 && texelFetch(maskTex, p, 0).r == 0u) {\n"
	"        int mw = textureSize(maskTex, 0).x;\n"
	"        if (p.x < uMargin || p.x >= mw - uMargin) {\n"
	"            // wide gaussian vertical blur: the sky's cloud BANDS are many\n"
	"            // pixels tall, so a narrow window only softens their edges. A\n"
	"            // ~1/10-screen-tall window dissolves them into the smooth\n"
	"            // gradient a stretched sky should be. The horizon (sky->terrain)\n"
	"            // blends over that span too, which reads as atmospheric haze\n"
	"            // rather than a hard streak line.\n"
	"            int sz = textureSize(maskTex, 0).y;\n"
	"            int r = max(4, sz / 24);\n"
	"            float sig = float(r) * 0.5;\n"
	"            vec3 acc = vec3(0.0);\n"
	"            float wsum = 0.0;\n"
	"            for (int dy = -r; dy <= r; dy++) {\n"
	"                float wt = exp(-float(dy * dy) / (2.0 * sig * sig));\n"
	"                acc += wt * fetch_at(ivec2(p.x, p.y + dy));\n"
	"                wsum += wt;\n"
	"            }\n"
	"            return acc / wsum;\n"
	"        }\n"
	"    }\n"
	"    return fetch_at(p);\n"
	"}\n"
	"\n"
	"vec3 fetch_rgb(vec2 tuv) { return fetch_smooth(src_px(tuv)); }\n"
	"\n"
	"void main() {\n"
	"    if (uCrt == 0) {                       // raw path - untouched product look\n"
	"        color = vec4(fetch_rgb(uv), 1.0);\n"
	"        return;\n"
	"    }\n"
	"\n"
	"    // ---- tube geometry: gentle barrel warp, black outside the glass ----\n"
	"    vec2 c = uv * 2.0 - 1.0;\n"
	"    c *= vec2(1.0 + 0.041 * c.y * c.y, 1.0 + 0.052 * c.x * c.x);\n"
	"    vec2 wuv = c * 0.5 + 0.5;\n"
	"    if (any(lessThan(wuv, vec2(0.0))) || any(greaterThan(wuv, vec2(1.0)))) {\n"
	"        color = vec4(0.0, 0.0, 0.0, 1.0);\n"
	"        return;\n"
	"    }\n"
	"    // ---- horizontal beam softness: 3-tap blur in fine pixels ----\n"
	"    ivec2 p = src_px(wuv);\n"
	"    int s = max(1, int(float(textureSize(idxTex, 0).y) / uSrcH * 0.45));\n"
	"    vec3 rgb = 0.5 * fetch_smooth(p)\n"
	"             + 0.25 * fetch_smooth(p + ivec2(s, 0))\n"
	"             + 0.25 * fetch_smooth(p - ivec2(s, 0));\n"
	"\n"
	"    // ---- scanlines: gaussian beam per source line, bright beams bloom ----\n"
	"    float d = fract(wuv.y * uSrcH) - 0.5;\n"
	"    float lum = dot(rgb, vec3(0.299, 0.587, 0.114));\n"
	"    float width = mix(0.35, 0.65, lum);\n"
	"    float scan = exp(-(d * d) / (2.0 * width * width));\n"
	"\n"
	"    // ---- shadow mask: two-phase magenta/green (rainbow-free at any res) ----\n"
	"    vec3 mask = ((int(gl_FragCoord.x) & 1) == 0)\n"
	"        ? vec3(1.0, 0.62, 1.0) : vec3(0.62, 1.0, 0.62);\n"
	"\n"
	"    // ---- rounded corners + vignette ----\n"
	"    vec2 cc = abs(wuv * 2.0 - 1.0);\n"
	"    float cornerd = length(max(cc - vec2(0.94), 0.0)) / 0.06;\n"
	"    float cornerm = 1.0 - smoothstep(0.8, 1.0, cornerd);\n"
	"    float vig = 1.0 - 0.10 * dot(cc, cc);\n"
	"\n"
	"    rgb *= scan * cornerm * vig * 1.42;\n"
	"    color = vec4(min(rgb * mask, 1.0), 1.0);\n"
	"}\n"
	"\n";

static const char *MVGL_MENU_VS =
	"\n"
	"#version 430\n"
	"uniform vec4 uRect;    // x, y, w, h in window pixels, y-down from top-left\n"
	"uniform vec2 uScreen;  // window size\n"
	"out vec2 uv;\n"
	"void main() {\n"
	"    vec2 p = vec2(float(gl_VertexID & 1), float((gl_VertexID >> 1) & 1));\n"
	"    uv = p;\n"
	"    vec2 px = uRect.xy + p * uRect.zw;\n"
	"    gl_Position = vec4(px.x / uScreen.x * 2.0 - 1.0,\n"
	"                       1.0 - px.y / uScreen.y * 2.0, 0.0, 1.0);\n"
	"}\n"
	"\n";

static const char *MVGL_MENU_FS =
	"\n"
	"#version 430\n"
	"uniform sampler2D uTex;   // A8 label bitmap\n"
	"uniform vec4 uColor;      // rgb tint, a = opacity\n"
	"uniform int uSolid;       // 1 = ignore texture (solid fill)\n"
	"in vec2 uv;\n"
	"out vec4 color;\n"
	"void main() {\n"
	"    float a = (uSolid == 1) ? 1.0 : texture(uTex, uv).r;\n"
	"    color = vec4(uColor.rgb, uColor.a * a);\n"
	"}\n"
	"\n";

