// GENERATED from cruisn-collection/gpu/zeus_renderer.py (menu from gpu/renderer.py) - regenerate with harness/gen_shaders.py, never hand-edit

static const char *MZGL_VS =
	"\n"
	"#version 430\n"
	"uniform vec2 uCanvas;      // canvas W (incl margins), FB_H (coarse)\n"
	"uniform float uMargin;     // 16:9 side margin (coarse px); shifts all x\n"
	"in vec2 in_pos;            // x, y (quad-local, coarse pixels)\n"
	"in float in_rowbase;       // renderRegs[0x4] row offset\n"
	"in vec4 in_p;              // p0 (z 12.12), p1 (u/z), p2 (v/z), p3 (1/z)\n"
	"in uvec4 in_meta0;         // flags, texbase(byte), texwidth, texmode\n"
	"in uvec4 in_meta1;         // transcolor, solidcolor, palidx, srcAlpha\n"
	"in uvec2 in_meta2;         // dstAlpha, zbuf_min(as u32)\n"
	"out vec4 p;\n"
	"flat out uvec4 meta0;\n"
	"flat out uvec4 meta1;\n"
	"flat out uvec2 meta2;\n"
	"void main() {\n"
	"    p = in_p;\n"
	"    meta0 = in_meta0; meta1 = in_meta1; meta2 = in_meta2;\n"
	"    // no y flip: FB row order == GL texture row order end-to-end\n"
	"    float y = in_pos.y + in_rowbase;\n"
	"    gl_Position = vec4((in_pos.x + uMargin) / uCanvas.x * 2.0 - 1.0,\n"
	"                       y / uCanvas.y * 2.0 - 1.0, 0.0, 1.0);\n"
	"}\n"
	"\n";

static const char *MZGL_FS =
	"\n"
	"#version 430\n"
	"uniform usampler2D waveram;   // 4096x4096 R8UI (16 MB)\n"
	"uniform usampler2D palTex;    // 256 x NPAL R32UI\n"
	"in vec4 p;                    // interpolated params\n"
	"flat in uvec4 meta0;          // flags, texbase, texwidth, texmode\n"
	"flat in uvec4 meta1;          // transcolor, solidcolor, palidx, srcAlpha\n"
	"flat in uvec2 meta2;          // dstAlpha, zbuf_min\n"
	"out vec4 color;\n"
	"\n"
	"const int WAVE_MASK = 0xFFFFFF;\n"
	"\n"
	"uint wave8(int idx) {\n"
	"    idx &= WAVE_MASK;\n"
	"    return texelFetch(waveram, ivec2(idx & 4095, idx >> 12), 0).r;\n"
	"}\n"
	"\n"
	"// swizzled texel fetchers (zeus2.h; plain byte addressing on LE)\n"
	"uint texel_4bit_2x2(int base, int y, int x, int w) {\n"
	"    int off = (y >> 2) * (w * 4) + ((x >> 2) << 3) + ((y & 3) << 1) + ((x >> 1) & 1);\n"
	"    return (wave8(base + off) >> ((x & 1) << 2)) & 0x0fu;\n"
	"}\n"
	"uint texel_8bit_4x2(int base, int y, int x, int w) {\n"
	"    int off = (y >> 1) * (w * 2) + ((x >> 2) << 3) + ((y & 1) << 2) + (x & 3);\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint texel_8bit_2x2(int base, int y, int x, int w) {\n"
	"    int off = (y >> 2) * (w * 4) + ((x >> 1) << 3) + ((y & 3) << 1) + (x & 1);\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint texel_alpha_t(int base, int y, int x, int w) {\n"
	"    int off = ((y >> 1) * (w * 2) + ((x >> 1) << 2) + ((y & 1) << 1) + (x & 1)) << 1;\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint texel_alpha_a(int base, int y, int x, int w) {\n"
	"    int off = (((y >> 1) * (w * 2) + ((x >> 1) << 2) + ((y & 1) << 1) + (x & 1)) << 1) + 1;\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint rgb555_at(int base, int y, int x, int w) {\n"
	"    int off = (y >> 1) * (w * 2) + ((x >> 1) << 2) + ((y & 1) << 1) + (x & 1);\n"
	"    int b = base + off * 2;\n"
	"    uint c = wave8(b) | (wave8(b + 1) << 8);\n"
	"    return c;\n"
	"}\n"
	"\n"
	"uint fetch(int mode, int base, int y, int x, int w) {\n"
	"    if (mode == 0) return texel_4bit_2x2(base, y, x, w);\n"
	"    if (mode == 1) return texel_8bit_4x2(base, y, x, w);\n"
	"    return texel_8bit_2x2(base, y, x, w);\n"
	"}\n"
	"\n"
	"uvec3 pal_rgb(uint idx, uint palrow) {\n"
	"    uint c = texelFetch(palTex, ivec2(int(idx), int(palrow)), 0).r;\n"
	"    return uvec3((c >> 16) & 0xffu, (c >> 8) & 0xffu, c & 0xffu);\n"
	"}\n"
	"\n"
	"// rgbaint_t::bilinear_filter (SSE path): row lerps halved into 16 bits\n"
	"uvec3 bilerp(uvec3 c00, uvec3 c01, uvec3 c10, uvec3 c11, uint u, uint v) {\n"
	"    u &= 0xffu; v &= 0xffu;\n"
	"    uvec3 r0 = c01 * u + c00 * (256u - u);\n"
	"    uvec3 r1 = c11 * u + c10 * (256u - u);\n"
	"    return min(((r1 >> 1) * v + (r0 >> 1) * (256u - v)) >> 15, uvec3(255u));\n"
	"}\n"
	"\n"
	"void main() {\n"
	"    uint flags = meta0.x;\n"
	"    int  texbase = int(meta0.y);\n"
	"    int  texw = int(meta0.z);\n"
	"    int  texmode = int(meta0.w & 3u);\n"
	"    uint transcolor = meta1.x;\n"
	"    uint palrow = meta1.z;\n"
	"    uint srcA = meta1.w;\n"
	"    uint dstA = meta2.x;\n"
	"    int  zmin = int(meta2.y);\n"
	"\n"
	"    // ---- zeus2 depth value ----\n"
	"    int curz = int(p.x);\n"
	"    int dv;\n"
	"    if ((flags & 32u) != 0u)      dv = 0xffffff;          // depth_clear\n"
	"    else if ((flags & 4u) != 0u)  dv = (flags & 512u) != 0u ? max(curz,zmin) : curz + zmin;\n"
	"    else                          dv = curz;\n"
	"    dv = clamp(dv, 0, 0xffffff);\n"
	"    gl_FragDepth = float(dv) / 16777215.0;\n"
	"\n"
	"    if ((flags & 256u) != 0u) {\n"
	"        // raw fill: fast clears and frame_writes replayed as rectangles -\n"
	"        // RGB24 in meta1.y, depth from p.x, no blend/texture\n"
	"        uint fc = meta1.y;\n"
	"        color = vec4(vec3(uvec3((fc >> 16) & 0xffu, (fc >> 8) & 0xffu,\n"
	"                                fc & 0xffu)) / 255.0, 0.0);\n"
	"        return;\n"
	"    }\n"
	"\n"
	"    bool blend = (flags & 2u) != 0u;\n"
	"    if (blend && srcA == 0u) discard;\n"
	"\n"
	"    // ---- perspective texel coords ----\n"
	"    float oozinv = 1.0 / p.w;\n"
	"    int curu = int(p.y * oozinv);\n"
	"    int curv = int(p.z * oozinv);\n"
	"    int u0 = max(curu >> 8, 0);\n"
	"    int v0 = max(curv >> 8, 0);\n"
	"    int u1 = u0 + 1;\n"
	"    int v1 = v0 + 1;\n"
	"\n"
	"    uvec3 src;\n"
	"    float outA = float(dstA) / 256.0;       // dst blend factor via alpha\n"
	"\n"
	"    if ((flags & 1u) != 0u) {               // solid RGB555 fill\n"
	"        uint sc = meta1.y;\n"
	"        src = uvec3((sc & 0x7c00u) >> 7, (sc & 0x3e0u) >> 2, (sc & 0x1fu) << 3);\n"
	"        if (blend && srcA != 0x100u) src = (src * srcA) >> 8;\n"
	"        if (!blend) outA = 1.0;\n"
	"    } else if ((flags & 128u) != 0u) {      // direct RGB555 texture\n"
	"        uint c = rgb555_at(texbase, v0, u0, texw);\n"
	"        src = uvec3((c & 0x7c00u) >> 7, (c & 0x3e0u) >> 2, (c & 0x1fu) << 3);\n"
	"        outA = 0.0;                         // plain overwrite, no blending\n"
	"    } else if ((flags & 64u) != 0u) {       // texture with embedded alpha\n"
	"        uint a00 = texel_alpha_a(texbase, v0, u0, texw);\n"
	"        uint a01 = texel_alpha_a(texbase, v0, u1, texw);\n"
	"        uint a10 = texel_alpha_a(texbase, v1, u0, texw);\n"
	"        uint a11 = texel_alpha_a(texbase, v1, u1, texw);\n"
	"        uint uF = uint(curu) & 0xffu;\n"
	"        uint vF = uint(curv) & 0xffu;\n"
	"        uint sA = ((a00 * (256u - uF) + a01 * uF) * (256u - vF)\n"
	"                 + (a10 * (256u - uF) + a11 * uF) * vF) >> 16;\n"
	"        if (sA == 0u) discard;\n"
	"        uvec3 c00 = pal_rgb(texel_alpha_t(texbase, v0, u0, texw), palrow);\n"
	"        uvec3 c01 = pal_rgb(texel_alpha_t(texbase, v0, u1, texw), palrow);\n"
	"        uvec3 c10 = pal_rgb(texel_alpha_t(texbase, v1, u0, texw), palrow);\n"
	"        uvec3 c11 = pal_rgb(texel_alpha_t(texbase, v1, u1, texw), palrow);\n"
	"        src = (bilerp(c00, c01, c10, c11, uint(curu), uint(curv)) * sA) >> 8;\n"
	"        outA = float(0x100u - sA) / 256.0;\n"
	"    } else {                                // palette texture\n"
	"        uint t00 = fetch(texmode, texbase, v0, u0, texw);\n"
	"        uint t01 = fetch(texmode, texbase, v0, u1, texw);\n"
	"        uint t10 = fetch(texmode, texbase, v1, u0, texw);\n"
	"        uint t11 = fetch(texmode, texbase, v1, u1, texw);\n"
	"        if (t00 == transcolor || t01 == transcolor\n"
	"            || t10 == transcolor || t11 == transcolor) discard;\n"
	"        uvec3 c00 = pal_rgb(t00, palrow);\n"
	"        uvec3 c01 = pal_rgb(t01, palrow);\n"
	"        uvec3 c10 = pal_rgb(t10, palrow);\n"
	"        uvec3 c11 = pal_rgb(t11, palrow);\n"
	"        src = bilerp(c00, c01, c10, c11, uint(curu), uint(curv));\n"
	"        if (blend && srcA != 0x100u) src = (src * srcA) >> 8;\n"
	"        if (!blend) outA = 1.0;\n"
	"    }\n"
	"    color = vec4(vec3(src) / 255.0, outA);\n"
	"}\n"
	"\n";

static const char *MZGL_PRESENT_VS =
	"\n"
	"#version 430\n"
	"out vec2 uv;\n"
	"void main() {  // full-screen triangle\n"
	"    vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);\n"
	"    uv = p;\n"
	"    gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);\n"
	"}\n"
	"\n";

static const char *MZGL_PRESENT_FS =
	"\n"
	"#version 430\n"
	"uniform sampler2D fbTex;     // RGBA8 512*S x 2048*S frame-buffer space\n"
	"uniform int uScale;\n"
	"uniform int uBaseRow;        // display base row (coarse; from zb38)\n"
	"uniform int uCrt;            // 1 = CRT pass, 0 = raw\n"
	"uniform float uSrcH;         // 400\n"
	"uniform float uSampW;        // source sample width (coarse): 3D=canvas, 2D=512\n"
	"uniform float uSampX0;       // source x start (coarse): 3D=0, 2D=margin\n"
	"in vec2 uv;\n"
	"out vec4 color;\n"
	"\n"
	"vec3 fetch_at(ivec2 p) { return texelFetch(fbTex, p, 0).rgb; }\n"
	"\n"
	"ivec2 src_px(vec2 tuv) {\n"
	"    float ry = float(uBaseRow) + (1.0 - tuv.y) * uSrcH;\n"
	"    return ivec2(int((uSampX0 + tuv.x * uSampW) * float(uScale)),\n"
	"                 int(ry * float(uScale)));\n"
	"}\n"
	"\n"
	"void main() {\n"
	"    if (uCrt == 0) {\n"
	"        color = vec4(fetch_at(src_px(uv)), 1.0);\n"
	"        return;\n"
	"    }\n"
	"    vec2 c = uv * 2.0 - 1.0;\n"
	"    c *= vec2(1.0 + 0.041 * c.y * c.y, 1.0 + 0.052 * c.x * c.x);\n"
	"    vec2 wuv = c * 0.5 + 0.5;\n"
	"    if (any(lessThan(wuv, vec2(0.0))) || any(greaterThan(wuv, vec2(1.0)))) {\n"
	"        color = vec4(0.0, 0.0, 0.0, 1.0);\n"
	"        return;\n"
	"    }\n"
	"    ivec2 p = src_px(wuv);\n"
	"    int s = max(1, uScale / 2);\n"
	"    vec3 rgb = 0.5 * fetch_at(p)\n"
	"             + 0.25 * fetch_at(p + ivec2(s, 0))\n"
	"             + 0.25 * fetch_at(p - ivec2(s, 0));\n"
	"    float d = fract(wuv.y * uSrcH) - 0.5;\n"
	"    float lum = dot(rgb, vec3(0.299, 0.587, 0.114));\n"
	"    float width = mix(0.35, 0.65, lum);\n"
	"    float scan = exp(-(d * d) / (2.0 * width * width));\n"
	"    vec3 mask = ((int(gl_FragCoord.x) & 1) == 0)\n"
	"        ? vec3(1.0, 0.62, 1.0) : vec3(0.62, 1.0, 0.62);\n"
	"    vec2 cc = abs(wuv * 2.0 - 1.0);\n"
	"    float cornerd = length(max(cc - vec2(0.94), 0.0)) / 0.06;\n"
	"    float cornerm = 1.0 - smoothstep(0.8, 1.0, cornerd);\n"
	"    float vig = 1.0 - 0.10 * dot(cc, cc);\n"
	"    rgb *= scan * cornerm * vig * 1.42;\n"
	"    color = vec4(min(rgb * mask, 1.0), 1.0);\n"
	"}\n"
	"\n";

static const char *MZGL_DEPTH_COMPAT_FS =
	"\n"
	"#version 430\n"
	"uniform usampler2D waveram;   // 4096x4096 R8UI (16 MB)\n"
	"uniform usampler2D palTex;    // 256 x NPAL R32UI\n"
	"in vec4 p;                    // interpolated params\n"
	"flat in uvec4 meta0;          // flags, texbase, texwidth, texmode\n"
	"flat in uvec4 meta1;          // transcolor, solidcolor, palidx, srcAlpha\n"
	"flat in uvec2 meta2;          // dstAlpha, zbuf_min\n"
	"out vec4 color;\n"
	"\n"
	"const int WAVE_MASK = 0xFFFFFF;\n"
	"\n"
	"uint wave8(int idx) {\n"
	"    idx &= WAVE_MASK;\n"
	"    return texelFetch(waveram, ivec2(idx & 4095, idx >> 12), 0).r;\n"
	"}\n"
	"\n"
	"// swizzled texel fetchers (zeus2.h; plain byte addressing on LE)\n"
	"uint texel_4bit_2x2(int base, int y, int x, int w) {\n"
	"    int off = (y >> 2) * (w * 4) + ((x >> 2) << 3) + ((y & 3) << 1) + ((x >> 1) & 1);\n"
	"    return (wave8(base + off) >> ((x & 1) << 2)) & 0x0fu;\n"
	"}\n"
	"uint texel_8bit_4x2(int base, int y, int x, int w) {\n"
	"    int off = (y >> 1) * (w * 2) + ((x >> 2) << 3) + ((y & 1) << 2) + (x & 3);\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint texel_8bit_2x2(int base, int y, int x, int w) {\n"
	"    int off = (y >> 2) * (w * 4) + ((x >> 1) << 3) + ((y & 3) << 1) + (x & 1);\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint texel_alpha_t(int base, int y, int x, int w) {\n"
	"    int off = ((y >> 1) * (w * 2) + ((x >> 1) << 2) + ((y & 1) << 1) + (x & 1)) << 1;\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint texel_alpha_a(int base, int y, int x, int w) {\n"
	"    int off = (((y >> 1) * (w * 2) + ((x >> 1) << 2) + ((y & 1) << 1) + (x & 1)) << 1) + 1;\n"
	"    return wave8(base + off);\n"
	"}\n"
	"uint rgb555_at(int base, int y, int x, int w) {\n"
	"    int off = (y >> 1) * (w * 2) + ((x >> 1) << 2) + ((y & 1) << 1) + (x & 1);\n"
	"    int b = base + off * 2;\n"
	"    uint c = wave8(b) | (wave8(b + 1) << 8);\n"
	"    return c;\n"
	"}\n"
	"\n"
	"uint fetch(int mode, int base, int y, int x, int w) {\n"
	"    if (mode == 0) return texel_4bit_2x2(base, y, x, w);\n"
	"    if (mode == 1) return texel_8bit_4x2(base, y, x, w);\n"
	"    return texel_8bit_2x2(base, y, x, w);\n"
	"}\n"
	"\n"
	"uvec3 pal_rgb(uint idx, uint palrow) {\n"
	"    uint c = texelFetch(palTex, ivec2(int(idx), int(palrow)), 0).r;\n"
	"    return uvec3((c >> 16) & 0xffu, (c >> 8) & 0xffu, c & 0xffu);\n"
	"}\n"
	"\n"
	"// rgbaint_t::bilinear_filter (SSE path): row lerps halved into 16 bits\n"
	"uvec3 bilerp(uvec3 c00, uvec3 c01, uvec3 c10, uvec3 c11, uint u, uint v) {\n"
	"    u &= 0xffu; v &= 0xffu;\n"
	"    uvec3 r0 = c01 * u + c00 * (256u - u);\n"
	"    uvec3 r1 = c11 * u + c10 * (256u - u);\n"
	"    return min(((r1 >> 1) * v + (r0 >> 1) * (256u - v)) >> 15, uvec3(255u));\n"
	"}\n"
	"\n"
	"void main() {\n"
	"    uint flags = meta0.x;\n"
	"    int  texbase = int(meta0.y);\n"
	"    int  texw = int(meta0.z);\n"
	"    int  texmode = int(meta0.w & 3u);\n"
	"    uint transcolor = meta1.x;\n"
	"    uint palrow = meta1.z;\n"
	"    uint srcA = meta1.w;\n"
	"    uint dstA = meta2.x;\n"
	"    int  zmin = int(meta2.y);\n"
	"\n"
	"    // ---- zeus2 depth value ----\n"
	"    int curz = int(p.x);\n"
	"    int dv;\n"
	"    if ((flags & 32u) != 0u)      dv = 0xffffff;          // depth_clear\n"
	"    else if ((flags & 4u) != 0u)  dv = (flags & 512u) != 0u ? max(curz,zmin) : curz + zmin;\n"
	"    else                          dv = curz;\n"
	"    dv = clamp(dv, 0, 0xffffff);\n"
	"    float legacyDepth = float(dv) / 16777215.0;\n"
	"    uint quantizedDepth = uint(floor(double(legacyDepth) * 16777215.0lf + 0.5lf));\n"
	"    gl_FragDepth = quantizedDepth == 16777215u ? 1.0 : float(quantizedDepth) / 67108864.0;\n"
	"\n"
	"    if ((flags & 256u) != 0u) {\n"
	"        // raw fill: fast clears and frame_writes replayed as rectangles -\n"
	"        // RGB24 in meta1.y, depth from p.x, no blend/texture\n"
	"        uint fc = meta1.y;\n"
	"        color = vec4(vec3(uvec3((fc >> 16) & 0xffu, (fc >> 8) & 0xffu,\n"
	"                                fc & 0xffu)) / 255.0, 0.0);\n"
	"        return;\n"
	"    }\n"
	"\n"
	"    bool blend = (flags & 2u) != 0u;\n"
	"    if (blend && srcA == 0u) discard;\n"
	"\n"
	"    // ---- perspective texel coords ----\n"
	"    float oozinv = 1.0 / p.w;\n"
	"    int curu = int(p.y * oozinv);\n"
	"    int curv = int(p.z * oozinv);\n"
	"    int u0 = max(curu >> 8, 0);\n"
	"    int v0 = max(curv >> 8, 0);\n"
	"    int u1 = u0 + 1;\n"
	"    int v1 = v0 + 1;\n"
	"\n"
	"    uvec3 src;\n"
	"    float outA = float(dstA) / 256.0;       // dst blend factor via alpha\n"
	"\n"
	"    if ((flags & 1u) != 0u) {               // solid RGB555 fill\n"
	"        uint sc = meta1.y;\n"
	"        src = uvec3((sc & 0x7c00u) >> 7, (sc & 0x3e0u) >> 2, (sc & 0x1fu) << 3);\n"
	"        if (blend && srcA != 0x100u) src = (src * srcA) >> 8;\n"
	"        if (!blend) outA = 1.0;\n"
	"    } else if ((flags & 128u) != 0u) {      // direct RGB555 texture\n"
	"        uint c = rgb555_at(texbase, v0, u0, texw);\n"
	"        src = uvec3((c & 0x7c00u) >> 7, (c & 0x3e0u) >> 2, (c & 0x1fu) << 3);\n"
	"        outA = 0.0;                         // plain overwrite, no blending\n"
	"    } else if ((flags & 64u) != 0u) {       // texture with embedded alpha\n"
	"        uint a00 = texel_alpha_a(texbase, v0, u0, texw);\n"
	"        uint a01 = texel_alpha_a(texbase, v0, u1, texw);\n"
	"        uint a10 = texel_alpha_a(texbase, v1, u0, texw);\n"
	"        uint a11 = texel_alpha_a(texbase, v1, u1, texw);\n"
	"        uint uF = uint(curu) & 0xffu;\n"
	"        uint vF = uint(curv) & 0xffu;\n"
	"        uint sA = ((a00 * (256u - uF) + a01 * uF) * (256u - vF)\n"
	"                 + (a10 * (256u - uF) + a11 * uF) * vF) >> 16;\n"
	"        if (sA == 0u) discard;\n"
	"        uvec3 c00 = pal_rgb(texel_alpha_t(texbase, v0, u0, texw), palrow);\n"
	"        uvec3 c01 = pal_rgb(texel_alpha_t(texbase, v0, u1, texw), palrow);\n"
	"        uvec3 c10 = pal_rgb(texel_alpha_t(texbase, v1, u0, texw), palrow);\n"
	"        uvec3 c11 = pal_rgb(texel_alpha_t(texbase, v1, u1, texw), palrow);\n"
	"        src = (bilerp(c00, c01, c10, c11, uint(curu), uint(curv)) * sA) >> 8;\n"
	"        outA = float(0x100u - sA) / 256.0;\n"
	"    } else {                                // palette texture\n"
	"        uint t00 = fetch(texmode, texbase, v0, u0, texw);\n"
	"        uint t01 = fetch(texmode, texbase, v0, u1, texw);\n"
	"        uint t10 = fetch(texmode, texbase, v1, u0, texw);\n"
	"        uint t11 = fetch(texmode, texbase, v1, u1, texw);\n"
	"        if (t00 == transcolor || t01 == transcolor\n"
	"            || t10 == transcolor || t11 == transcolor) discard;\n"
	"        uvec3 c00 = pal_rgb(t00, palrow);\n"
	"        uvec3 c01 = pal_rgb(t01, palrow);\n"
	"        uvec3 c10 = pal_rgb(t10, palrow);\n"
	"        uvec3 c11 = pal_rgb(t11, palrow);\n"
	"        src = bilerp(c00, c01, c10, c11, uint(curu), uint(curv));\n"
	"        if (blend && srcA != 0x100u) src = (src * srcA) >> 8;\n"
	"        if (!blend) outA = 1.0;\n"
	"    }\n"
	"    color = vec4(vec3(src) / 255.0, outA);\n"
	"}\n"
	"\n";

static const char *MZGL_MENU_VS =
	"\n"
	"#version 430\n"
	"uniform vec4 uRect;    // x, y, w, h in window pixels, y-down from top-left\n"
	"uniform vec2 uScreen;  // window size\n"
	"out vec2 uv;\n"
	"void main() {\n"
	"    vec2 p = vec2(float(gl_VertexID & 1), float((gl_VertexID >> 1) & 1));\n"
	"    uv = p;\n"
	"    vec2 px = uRect.xy + p * uRect.zw;\n"
	"    gl_Position = vec4(px.x / uScreen.x * 2.0 - 1.0,\n"
	"                       1.0 - px.y / uScreen.y * 2.0, 0.0, 1.0);\n"
	"}\n"
	"\n";

static const char *MZGL_MENU_FS =
	"\n"
	"#version 430\n"
	"uniform sampler2D uTex;   // A8 label bitmap\n"
	"uniform vec4 uColor;      // rgb tint, a = opacity\n"
	"uniform int uSolid;       // 1 = ignore texture (solid fill)\n"
	"in vec2 uv;\n"
	"out vec4 color;\n"
	"void main() {\n"
	"    float a = (uSolid == 1) ? 1.0 : texture(uTex, uv).r;\n"
	"    color = vec4(uColor.rgb, uColor.a * a);\n"
	"}\n"
	"\n";

